package l2j.lexer.token;

public enum InstructionTypes {
	FNEG, ADD, FADD, SUB, FSUB, MUL, FMUL, UDIV, SDIV, FDIV, UREM, SREM, FREM, SHL, LSHR, ASHR, AND, OR, XOR, ICMP,
	FCMP, PHI, CALL, TRUNC, ZEXT, SEXT, FPTRUNC, FPEXT, UITOFP, SITOFP, FPTOUI, FPTOSI, INTTOPTR, PTRTOINT, BITCAST,
	ADDRSPACECAST, SELECT, VA_ARG, RET, BR, SWITCH, INDIRECTBR, INVOKE, RESUME, UNREACHABLE, CALLBR, ALLOCA, LOAD,
	STORE, CMPXCHG, ATOMICRMW, FENCE, GETELEMENTPTR, EXTRACTELEMENT, INSERTELEMENT, SHUFFLEVECTOR, EXTRACTVALUE,
	INSERTVALUE, LANDINGPAD, CLEANUPRET, CATCHRET, CATCHSWITCH, CATCHPAD, CLEANUPPAD
}
